spring:
  config:
    name: spare
#注册的地址
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 #启用主动失效
    enable-self-preservation: true #关闭自我保护
  instance:
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置
    prefer-ip-address: true
    ip-address: 192.168.0.3
    instance-id:  ${eureka.instance.ip-address}:${server.port}
  client:
    #是否向自己注册, 不注册
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:123456@192.168.0.2:8761/eureka/
    registry-fetch-interval-seconds: 5 #client刷新本地缓存时间